### ISSUE TITLE
Error: config.privateKey does not exist at given fs path

### ISSUE THREAD

**Issue by julesghub** [garygrossgarten/github-action-ssh#11]
I'm getting:
`Error: config.privateKey does not exist at given fs path`

when I use the privateKey / passphase authenication in the following action step.

```
    - name: ls on gadi
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ls -a
        host: "gadi.nci.org.au"
        username: ${{ secrets.GADI_UNAME }}
        #password: ${{ secrets.GADI_PWORD }}
        privateKey: ${{ secrets.GADI_PRIVATE_KEY }}
        passphrase: ${{ secrets.GADI_PASSPHRASE }}
```
What does this mean? 
Ideas on how I can fix it?

Note, when I use GADI_PWORD my action runs as expected.

cheers,
J
