### ISSUE TITLE
Exit not appended correctly

### ISSUE THREAD

**Issue by almostengr** [garygrossgarten/github-action-ssh#12]
When using the configuration below, 

```yml
    - name: Deploy code to production
      uses: fifsky/ssh-action@master
      with:
        command: ls
        host: ${{ secrets.HOSTS }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT_NUMBER }}
        user: ${{ secrets.USERNAME }}
```

this action ran the command "ls exit" on the server, which resulted in the below output. 

```bash
ls exit
Pseudo-terminal will not be allocated because stdin is not a terminal.
Start Run Command
load pubkey "/github/home/.ssh/deploy_key": invalid format
ls: cannot access exit: No such file or directory
```

The documentation does not mention that the ```exit``` command will be appended to the existing commands. As a result, it is not running the command that it should be. Based on the errors received, I had to modify my command to be 

```bash
ls &&
```

in order for the action to complete successfully.
