### ISSUE TITLE
Error: config.privateKey does not exist at given fs path

### ISSUE THREAD

**Issue by NoobTW** [garygrossgarten/github-action-ssh#18]
New version is not working. (I was able to do this 5 hours ago)

Here's my config:

```
- name: deploy using SSH
      uses: garygrossgarten/github-action-ssh@release
      id: remote
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command: |
          echo test
```

And here's the log.

> Establishing a SSH connection to ***.
> ⚠️ The GitHub Action couldn't connect to ***. AssertionError [ERR_ASSERTION]: config.privateKey does not exist at given fs path
>     at new AssertionError (internal/assert/assertion_error.js:418:11)
>     at NodeSSH.connect (/home/runner/_work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:10101:31) {
>   generatedMessage: false,
>   code: 'ERR_ASSERTION',
>   actual: undefined,
>   expected: undefined,
>   operator: undefined
> }
> Error: config.privateKey does not exist at given fs path

I have seen that there are a few updates (0.6.0 & 0.6.1), so maybe something breaks. Haven't check any code yet; just try to provide some information first.
