### ISSUE TITLE
Getting "All configured authentication methods failed" using private key (password-base is working) on a seemingly well-configured server

### ISSUE THREAD

**Issue by godstanis** [garygrossgarten/github-action-ssh#20]
First of all - password base authentication is working properly.

I'm trying to run commands on a VPS using private key, I've configured SSH there like this:

```sh
cd ~/.ssh
ssh-keygen -t rsa -b 4096 -C "test@example.com" # passphrase is empty
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
```

Then I copied the private key to my repo secrets from this file:
```sh
cat ~/.ssh/id_rsa
```

The key looks like this:
```
-----BEGIN RSA PRIVATE KEY-----
data...
-----END RSA PRIVATE KEY-----
```

Here is my workflow config:

```yaml
name: Deploy

on: 
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Updating and restarting the service on remote host
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.RR_HOST }} # ip address i use to access the server with 'ssh user@ip'
        username: ${{ secrets.RR_USERNAME }} # username "test@example.com"
        privateKey: ${{ secrets.RR_PRIVATE }} # private key of my VPS ~/.ssh/id_rsa file
        command: |
          cd dc-apps/go/linksmap/
          docker-compose down
          git reset --hard
          git pull
          go get ./...
          docker-compose up -d
```

When I try to run the job I get this:
```sh
Run garygrossgarten/github-action-ssh@release
  with:
    host: ***
    username: ***
    privateKey: ***
    command: cd dc-apps/go/linksmap/
  docker-compose down
  git reset --hard
  git pull
  go get ./...
  docker-compose up -d
  
    port: 22
(node:2404) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Establishing a SSH connection to ***.
using provided private key
⚠️ The GitHub Action couldn't connect to ***. Error: All configured authentication methods failed
    at doNextAuth (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:11803:17)
    at tryNextAuth (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:11874:5)
    at SSH2Stream.onUSERAUTH_FAILURE (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:11987:5)
    at SSH2Stream.emit (events.js:210:5)
    at parsePacket (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:16883:10)
    at SSH2Stream.module.exports.635.SSH2Stream._transform (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:13902:13)
    at SSH2Stream.Transform._read (_stream_transform.js:189:10)
    at SSH2Stream.module.exports.635.SSH2Stream._read (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:13454:15)
    at SSH2Stream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:431:12) {
  level: 'client-authentication'
}
⚠️ An error happened executing command cd dc-apps/go/linksmap/
docker-compose down
git reset --hard
git pull
go get ./...
docker-compose up -d. Not connected
Error: All configured authentication methods failed
Executing command: cd dc-apps/go/linksmap/
docker-compose down
git reset --hard
git pull
go get ./...
docker-compose up -d
Error: Not connected
 1: 0x9da7c0 node::Abort() [/home/runner/runners/2.275.1/externals/node12/bin/node]
 2: 0xa4e219  [/home/runner/runners/2.275.1/externals/node12/bin/node]
 3: 0xba5d59  [/home/runner/runners/2.275.1/externals/node12/bin/node]
 4: 0xba7b47 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/runner/runners/2.275.1/externals/node12/bin/node]
 5: 0x13750d9  [/home/runner/runners/2.275.1/externals/node12/bin/node]
```

What am I doing wrong here?

**Comment by godstanis** [comment]
Ok, I should have used my ssh login, not the email from `ssh-keygen` command

**Comment by AxelPariss** [comment]
Thank you @godstanis you describe what I needed to do 😅

I think it will be a good idea to add your "process" in the readme @garygrossgarten (maybe ?) 🤔

**Comment by garygrossgarten** [comment]
The readme could indeed bei improved. @AxelPariss Do you mind creating a PR?

**Comment by godstanis** [comment]
@AxelPariss I guess this process is pretty generic and you can google it like in 5 seconds, but why not :ok_hand:

**Comment by andreatoppan** [comment]
Seems newer Ubuntu 22.04 has changed default accepted key types and this plugin sometimes is not working, the solution for me was to generate the private key with a different algorithm:

`
cd ~/.ssh
ssh-keygen -t ecdsa -b 521 -C "test@example.com" # passphrase is empty
ssh-copy-id -i ~/.ssh/id_ecdsa.pub "test@example.com"
`

**Comment by anuj9196** [comment]
I'm using this action to SSH to the Oracle cloud instance using 
```yml

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: app-admin
          host: ${{ env.OCI_HOST }}
          username: ${{ env.SSH_USER }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
```
where using private key generated during the creation of the instance, but it gives the same error as in the first question.

However, SSH is working fine when used locally
```
ssh -i private-key ubuntu@ip-address
```
