### ISSUE TITLE
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper

### ISSUE THREAD

**Issue by AxharKhan** [garygrossgarten/github-action-ssh#27]
I know this is probably not an issue with this action but can I get some help with this, I am trying to restart a service on a ubuntu 20.04 server using this ssh action but I get this error.
```
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo service launchcentre restart
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        tryKeyboard: true
```
