### ISSUE TITLE
Cannot connect to host

### ISSUE THREAD

**Issue by Pzixel** [garygrossgarten/github-action-ssh#31]
I'm trying to run a script on remote machine. For some reason an action fails.

My workflow looks like this:

```yml
      - name: Deploy with rsync
	        run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/app/
	        
	      - name: Restart app
	        uses: garygrossgarten/github-action-ssh@release
	        with:
	          command: (cd /home/${{ secrets.SSH_USER }}/app/ && ./run.sh)
	          host: ${{ secrets.SSH_HOST }}
	          username: ${{ secrets.SSH_USER }}
	          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
	          passphrase: ''
```

Here is output:

[img]https://i.imgur.com/ITVVud6.png[/img]

As you can see `rsync` is working correctly and it was able to copy all files via SSH. However the next step `github-action-ssh` fails.

I'm not sure what to do here so here is an issue.
