### ISSUE TITLE
ENAMETOOLONG: name too long, open '***'

### ISSUE THREAD

**Issue by wyllisMonteiro** [garygrossgarten/github-action-ssh#32]
I'm trying to run a script on remote machine. For some reason an action fails.

**deploy job**
```
deploy:
    runs-on: ubuntu-latest

    needs: build
    if: github.ref == 'refs/heads/ci-1'
    steps:
    - name: Deploy to Server
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ls -a
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey : ${{ secrets.SSH_PRIVATE_KEY}}
```

I set my secrets as you can see
![2](https://user-images.githubusercontent.com/36091415/171288638-aa10ca85-7e6a-499a-8ccc-9f3b75310c4d.PNG)

I got this message
![1](https://user-images.githubusercontent.com/36091415/171288685-0634b8ee-4a93-462f-8ba9-b983884e6bb2.PNG)

It seems my hostname is too long but it's the good one. I tried to connect with command line ssh <username>@<hostname>, it work's well. I try to connect to ionos host via github action
