### ISSUE TITLE
Multiple commands

### ISSUE THREAD

**Issue by JungwooLee-GGQ** [garygrossgarten/github-action-ssh#38]
I have checked closed issue `Multiple` discussing execute multiple commands by break line but seems like it doesn't work for me
``` yaml
- name: connect and go cd
        uses: garygrossgarten/github-action-ssh@0.7.0
        with:
          host: ${{ matrix.server }}
          username: ${{ matrix.user }}
          privateKey: ${{ secrets.KEY}}
          command: | 
            echo "Testing"
            echo "DD"
            ipconfig
```
am i doing something wrong here? help plz
