### ISSUE TITLE
Github action workflow stuck suddenly stuck at some point and loading and loading. 

### ISSUE THREAD

**Issue by ravismakwana** [garygrossgarten/github-action-ssh#42]
Yes, there is no error showing while running the GitHub workflow, it was working before a week ago with same code. 
any one have idea about this? 

**automation-live.yml**
```
name: Commit on AWS EC2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ../../website/website/
          remote: /opt/bitnami/wordpress/wp-content/themes
          host: 35.159.119.129
          username: bitnami
          privateKey: ${{ secrets.PRODUCTION_KEY }}
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /opt/bitnami/wordpress/wp-content/themes/sherpa
            gulp
          host: 35.159.119.129
          user: bitnami
          key: ${{ secrets.PRODUCTION_KEY}}

```

I use this yml file where it was working before, don't know how can I solve this. 

![image](https://github.com/user-attachments/assets/287236d4-49c2-4f82-8960-7623dfe5686b)
