### ISSUE TITLE
Action succeeds even when the command exits with an error code

### ISSUE THREAD

**Issue by danports** [garygrossgarten/github-action-ssh#8]
This issue can be reproduced with a very simple action - the following succeeds when it should fail:

```yaml
      - name: Success against all odds
        uses: garygrossgarten/github-action-ssh@master
        with:
          command: bash -c 'exit 1'
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}    
```

**Comment by akoidan** [comment]
Any update? This one really bunkers. Maybe we can provide some help?)

**Comment by markdorison** [comment]
PR #16 was merged and is an improvement to this issue, but in my testing it only resolved it when the _final_ command exits with an error code.

If you pass multiple commands to the action, it will only exit with an error code if the _last_ command fails.

Action completes successfully:

```yaml
- name: Success against all odds
   uses: garygrossgarten/github-action-ssh@master
    with:
    command: |
      lsTYPO
      ls -lah
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    password: ${{ secrets.PASSWORD }}   
```

Action returns an error:
```yaml
- name: Success against all odds
   uses: garygrossgarten/github-action-ssh@master
    with:
    command: |
      ls -lah
      lsTYPO
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    password: ${{ secrets.PASSWORD }}   
```

**Comment by akoidan** [comment]
This is sad :( Since chains of libs that this package require ( `node-ssh` -> `ssh`) provide the API that reacts on the last command's exit code.

```
interface SSHExecCommandResponse {
    stdout: string;
    stderr: string;
    code: number | null;
    signal: string | null;
}
```

**Comment by akoidan** [comment]
I personally chosen to use simple bash script and pipe it into tar. Copying without tar (let's say using this plugin) takes 4 min. Copying via tar takes ~15 seconds.

```yaml
    - name: Setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Copy static files to destination server
        # Copying files by packing them into non-compress archive is a lot faster. It takes 8 seconds to copy all files instead of 4 minutes with packages like garygrossgarten/github-action-scp@release
        run: tar c dist/ | ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} "rm -rf /srv/http/vue/dist && tar x -C /srv/http/vue/"
```
